[workspace]
members = [
    "rust/ahweb",
    "rust/ah-chromiumd",
    "rust/ahnexus",
]
exclude = [
    "rust/ahsh",
    "vendor",
    "rust/proto/test-rust",
    "forks",
    "patches",
    "scripts",
    "bun",
    "docs",
    "node_modules",
    "target",
    "dist",
    "logs",
    "assets",
    "skills",
    "rust/ahtch",
    "rust/ebx",
]
resolver = "2"
