[workspace]
members = [
    "code/termsurf/rs/ahweb",
    "code/termsurf/rs/ah-chromiumd",
    "code/termsurf/rs/ahnexus",
    "code/earthbucks/rs/ebxlib",
    "code/earthbucks/rs/ebxfloat",
    "code/earthbucks/rs/ebxpow5",
    "code/earthbucks/rs/ebxmine",
]
exclude = [
    "code/termsurf/rs/ahsh",
    "vendor",
    "code/termsurf/proto/test-rust",
    "forks",
    "patches",
    "scripts",
    "docs",
    "node_modules",
    "target",
    "dist",
    "logs",
    "assets",
    "skills",
    "code/termsurf/rs/ahtch",
]
resolver = "2"
