/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hello.proto */

#ifndef PROTOBUF_C_hello_2eproto__INCLUDED
#define PROTOBUF_C_hello_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Termsurf__Hello Termsurf__Hello;


/* --- enums --- */


/* --- messages --- */

struct  Termsurf__Hello
{
  ProtobufCMessage base;
  char *name;
  int64_t id;
  uint64_t size;
  double x;
  protobuf_c_boolean active;
};
#define TERMSURF__HELLO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&termsurf__hello__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0 }


/* Termsurf__Hello methods */
void   termsurf__hello__init
                     (Termsurf__Hello         *message);
size_t termsurf__hello__get_packed_size
                     (const Termsurf__Hello   *message);
size_t termsurf__hello__pack
                     (const Termsurf__Hello   *message,
                      uint8_t             *out);
size_t termsurf__hello__pack_to_buffer
                     (const Termsurf__Hello   *message,
                      ProtobufCBuffer     *buffer);
Termsurf__Hello *
       termsurf__hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   termsurf__hello__free_unpacked
                     (Termsurf__Hello *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Termsurf__Hello_Closure)
                 (const Termsurf__Hello *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor termsurf__hello__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_hello_2eproto__INCLUDED */
