/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: hello.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "hello.pb-c.h"
void   termsurf__hello__init
                     (Termsurf__Hello         *message)
{
  static const Termsurf__Hello init_value = TERMSURF__HELLO__INIT;
  *message = init_value;
}
size_t termsurf__hello__get_packed_size
                     (const Termsurf__Hello *message)
{
  assert(message->base.descriptor == &termsurf__hello__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t termsurf__hello__pack
                     (const Termsurf__Hello *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &termsurf__hello__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t termsurf__hello__pack_to_buffer
                     (const Termsurf__Hello *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &termsurf__hello__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Termsurf__Hello *
       termsurf__hello__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Termsurf__Hello *)
     protobuf_c_message_unpack (&termsurf__hello__descriptor,
                                allocator, len, data);
}
void   termsurf__hello__free_unpacked
                     (Termsurf__Hello *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &termsurf__hello__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor termsurf__hello__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Termsurf__Hello, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Termsurf__Hello, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Termsurf__Hello, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Termsurf__Hello, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "active",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Termsurf__Hello, active),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned termsurf__hello__field_indices_by_name[] = {
  4,   /* field[4] = active */
  1,   /* field[1] = id */
  0,   /* field[0] = name */
  2,   /* field[2] = size */
  3,   /* field[3] = x */
};
static const ProtobufCIntRange termsurf__hello__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor termsurf__hello__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "termsurf.Hello",
  "Hello",
  "Termsurf__Hello",
  "termsurf",
  sizeof(Termsurf__Hello),
  5,
  termsurf__hello__field_descriptors,
  termsurf__hello__field_indices_by_name,
  1,  termsurf__hello__number_ranges,
  (ProtobufCMessageInit) termsurf__hello__init,
  NULL,NULL,NULL    /* reserved[123] */
};
