# ahtch.nu — GENERATED by `ahtch nu-module`; do not edit by hand.
# Regenerate: ahtch nu-module | save -f ahtch.nu
#
# Wrappers honor the dual input pattern: pipe the leftmost tensor in as
# $in, or pass handles as arguments — the CLI grammar fills missing slots.
# Handles are tensor://… strings; data converts at the boundary only.
# `ahtch <op>` is the primary Nushell namespace.

# Decode CLI JSON output, restoring the non-finite dialect tokens
# ("NaN"/"Infinity"/"-Infinity") to real Nushell floats.
def __nutorch-restore []: any -> any {
  let v = $in
  let t = ($v | describe)
  if ($t | str starts-with "list") or ($t | str starts-with "table") {
    $v | each { |x| $x | __nutorch-restore }
  } else if $t == "string" {
    match $v {
      "NaN" => ('NaN' | into float)
      "Infinity" => ('inf' | into float)
      "-Infinity" => ('-inf' | into float)
      _ => $v
    }
  } else { $v }
}

# Encode Nushell data for the CLI, replacing non-finite floats with the
# dialect tokens (nu's `to json` would silently emit null for them).
def __nutorch-encode []: any -> any {
  let v = $in
  let t = ($v | describe)
  if ($t | str starts-with "list") or ($t | str starts-with "table") {
    $v | each { |x| $x | __nutorch-encode }
  } else if $t == "float" {
    # Non-finite floats are detected by STRING form: nu 0.113's float
    # comparisons are unreliable for them (1.5 == inf is true; inf > 0
    # is false — probed), but `into string` is deterministic.
    match ($v | into string) {
      "NaN" => "NaN"
      "inf" => "Infinity"
      "-inf" => "-Infinity"
      _ => $v
    }
  } else { $v }
}

# Create a tensor from native Nushell data — as the argument or from $in
# (dual input, issue 0017): one encode path either way; an explicit
# argument wins and the pipe is silently ignored.
export def "ahtch tensor" [data?: any, --dtype: string, --requires-grad]: any -> string {
  mut args = []
  if $dtype != null { $args = ($args | append ["--dtype" $dtype]) }
  if $requires_grad { $args = ($args | append "--requires_grad") }
  let __in = $in
  let __data = if $data != null { $data } else { $__in }
  $__data | __nutorch-encode | to json -r | ^ahtch tensor ...$args | str trim
}

# Read a tensor back as native Nushell data — handle as the argument or
# from $in (dual input, issue 0017); the argument wins when both arrive.
export def "ahtch value" [handle?: string]: any -> any {
  let __in = $in
  let __out = if $handle != null { ^ahtch value $handle } else { $__in | ^ahtch value }
  $__out | from json | __nutorch-restore
}

# A tensor's dimensions as a native list of ints — handle as the argument
# or from $in (dual input, issue 0018); the argument wins when both arrive.
# No restore: dims are always finite ints, never the non-finite token dialect.
export def "ahtch shape" [handle?: string]: any -> list<int> {
  let __in = $in
  let __out = if $handle != null { ^ahtch shape $handle } else { $__in | ^ahtch shape }
  $__out | from json
}

# Free tensors: pipe a handle, a list of handles, or pass them as args.
export def "ahtch free" [...handles: string, --all]: any -> nothing {
  if $all {
    ^ahtch free --all
  } else if ($handles | is-empty) {
    let piped = $in
    let text = if (($piped | describe) | str starts-with "list") {
      $piped | str join (char newline)
    } else { $piped }
    $text | ^ahtch free
  } else {
    ^ahtch free ...$handles
  }
}

# The registry census as a native table.
export def "ahtch tensors" []: nothing -> table {
  ^ahtch tensors --json | from json
}

# The op table as a native table.
export def "ahtch ops" []: nothing -> table {
  ^ahtch ops --json | from json
}

# Daemon status as a native record.
export def --wrapped "ahtch daemon" [...rest: string]: nothing -> any {
  if $rest == ["status"] {
    ^ahtch daemon status --json | from json
  } else {
    ^ahtch daemon ...$rest
  }
}

# Module construction and verbs (passthrough; handles are strings).
# def --wrapped lets unknown flags (--lr, --momentum, …) flow into $rest.
export def --wrapped "ahtch nn" [...rest: string]: nothing -> any {
  if ($rest | first) == "info" {
    ^ahtch nn info ($rest | get 1) --json | from json
  } else {
    ^ahtch nn ...$rest | str trim
  }
}

# Run a module on a piped tensor handle.
export def "ahtch forward" [...rest: string]: any -> string {
  # Dual input (issue 0016): `$x | torch forward $m` or
  # `torch forward $m $x` — the CLI's grammar fills missing slots.
  let __in = $in
  let __out = if $__in == null { ^ahtch forward ...$rest } else { $__in | ^ahtch forward ...$rest }
  $__out | str trim
}

# One optimizer step (piped optimizer handle or argument).
export def "ahtch step" [optimizer?: string]: any -> nothing {
  if $optimizer != null {
    ^ahtch step $optimizer
  } else {
    $in | ^ahtch step
  }
}


# a + alpha*b (broadcasting; --alpha default 1)
# usage: ahtch add <t1> <t2> [--alpha <Scalar>]
export def "ahtch add" [...rest: any, --alpha: number]: any -> string {
  mut args = []
  if $alpha != null { $args = ($args | append ["--alpha" ($alpha | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch add ...$__rest ...$args } else { $__in | ^ahtch add ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch add" = torch add

# a - alpha*b (broadcasting; --alpha default 1)
# usage: ahtch sub <t1> <t2> [--alpha <Scalar>]
export def "ahtch sub" [...rest: any, --alpha: number]: any -> string {
  mut args = []
  if $alpha != null { $args = ($args | append ["--alpha" ($alpha | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sub ...$__rest ...$args } else { $__in | ^ahtch sub ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch sub" = torch sub

# elementwise sine
# usage: ahtch sin <t1>
export def "ahtch sin" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sin ...$__rest } else { $__in | ^ahtch sin ...$__rest }
  $__out | str trim
}

export alias "nutorch sin" = torch sin

# elementwise power (scalar or tensor exponent)
# usage: ahtch pow <t1> <exponent>
export def "ahtch pow" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch pow ...$__rest } else { $__in | ^ahtch pow ...$__rest }
  $__out | str trim
}

export alias "nutorch pow" = torch pow

# clamp into [min, max] (scalar or tensor bounds; one required)
# usage: ahtch clamp <t1> [--min <HandleOrScalar>] [--max <HandleOrScalar>]
export def "ahtch clamp" [...rest: any, --min: any, --max: any]: any -> string {
  mut args = []
  if $min != null { $args = ($args | append ["--min" ($min | into string)]) }
  if $max != null { $args = ($args | append ["--max" ($max | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch clamp ...$__rest ...$args } else { $__in | ^ahtch clamp ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch clamp" = torch clamp

# sum over all elements, or along --dim
# usage: ahtch sum <t1> [--dim <Int>] [--keepdim]
export def "ahtch sum" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sum ...$__rest ...$args } else { $__in | ^ahtch sum ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch sum" = torch sum

# mean over all elements, or along --dim (float32, v1 fidelity)
# usage: ahtch mean <t1> [--dim <Int>] [--keepdim]
export def "ahtch mean" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch mean ...$__rest ...$args } else { $__in | ^ahtch mean ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch mean" = torch mean

# elementwise equality (returns a Bool tensor)
# usage: ahtch eq <t1> <t2>
export def "ahtch eq" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch eq ...$__rest } else { $__in | ^ahtch eq ...$__rest }
  $__out | str trim
}

export alias "nutorch eq" = torch eq

# true if all elements are close (returns a JSON bool)
# usage: ahtch allclose <t1> <t2> [--rtol <Float>] [--atol <Float>]
export def "ahtch allclose" [...rest: any, --rtol: number, --atol: number]: any -> any {
  mut args = []
  if $rtol != null { $args = ($args | append ["--rtol" ($rtol | into string)]) }
  if $atol != null { $args = ($args | append ["--atol" ($atol | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch allclose ...$__rest ...$args } else { $__in | ^ahtch allclose ...$__rest ...$args }
  $__out | from json | __nutorch-restore
}

export alias "nutorch allclose" = torch allclose

# sort along --dim (default last); returns values and indices
# usage: ahtch sort <t1> [--dim <Int>] [--descending]
export def "ahtch sort" [...rest: any, --dim: int, --descending]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $descending { $args = ($args | append "--descending") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sort ...$__rest ...$args } else { $__in | ^ahtch sort ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch sort" = torch sort

# matrix multiply of two 2-D tensors
# usage: ahtch mm <t1> <t2>
export def "ahtch mm" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch mm ...$__rest } else { $__in | ^ahtch mm ...$__rest }
  $__out | str trim
}

export alias "nutorch mm" = torch mm

# concatenate tensors along --dim (default 0)
export def "ahtch cat" [...rest: string, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __piped = $in
  let __text = if ($__piped | describe | str starts-with "list") { $__piped | str join (char newline) } else if $__piped == null { "" } else { $__piped }
  $__text | ^ahtch cat ...$rest ...$args | str trim
}

export alias "nutorch cat" = torch cat

# a tensor of the given shape filled with a value
export def "ahtch full" [shape: list<int>, value: number, --dtype: string, --requires_grad]: nothing -> string {
  mut args = []
  if $dtype != null { $args = ($args | append ["--dtype" ($dtype | into string)]) }
  if $requires_grad { $args = ($args | append "--requires_grad") }
  ^ahtch full ($shape | to json -r) ($value | into string) ...$args | str trim
}

export alias "nutorch full" = torch full

# standard-normal random tensor (float kinds only)
export def "ahtch randn" [shape: list<int>, --dtype: string, --requires_grad]: nothing -> string {
  mut args = []
  if $dtype != null { $args = ($args | append ["--dtype" ($dtype | into string)]) }
  if $requires_grad { $args = ($args | append "--requires_grad") }
  ^ahtch randn ($shape | to json -r) ...$args | str trim
}

export alias "nutorch randn" = torch randn

# elementwise absolute value
# usage: ahtch abs <t1>
export def "ahtch abs" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch abs ...$__rest } else { $__in | ^ahtch abs ...$__rest }
  $__out | str trim
}

export alias "nutorch abs" = torch abs

# elementwise arccosine
# usage: ahtch acos <t1>
export def "ahtch acos" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch acos ...$__rest } else { $__in | ^ahtch acos ...$__rest }
  $__out | str trim
}

export alias "nutorch acos" = torch acos

# elementwise inverse hyperbolic cosine
# usage: ahtch acosh <t1>
export def "ahtch acosh" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch acosh ...$__rest } else { $__in | ^ahtch acosh ...$__rest }
  $__out | str trim
}

export alias "nutorch acosh" = torch acosh

# elementwise arcsine
# usage: ahtch asin <t1>
export def "ahtch asin" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch asin ...$__rest } else { $__in | ^ahtch asin ...$__rest }
  $__out | str trim
}

export alias "nutorch asin" = torch asin

# elementwise inverse hyperbolic sine
# usage: ahtch asinh <t1>
export def "ahtch asinh" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch asinh ...$__rest } else { $__in | ^ahtch asinh ...$__rest }
  $__out | str trim
}

export alias "nutorch asinh" = torch asinh

# elementwise arctangent
# usage: ahtch atan <t1>
export def "ahtch atan" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch atan ...$__rest } else { $__in | ^ahtch atan ...$__rest }
  $__out | str trim
}

export alias "nutorch atan" = torch atan

# elementwise inverse hyperbolic tangent
# usage: ahtch atanh <t1>
export def "ahtch atanh" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch atanh ...$__rest } else { $__in | ^ahtch atanh ...$__rest }
  $__out | str trim
}

export alias "nutorch atanh" = torch atanh

# elementwise ceiling
# usage: ahtch ceil <t1>
export def "ahtch ceil" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch ceil ...$__rest } else { $__in | ^ahtch ceil ...$__rest }
  $__out | str trim
}

export alias "nutorch ceil" = torch ceil

# elementwise cosine
# usage: ahtch cos <t1>
export def "ahtch cos" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch cos ...$__rest } else { $__in | ^ahtch cos ...$__rest }
  $__out | str trim
}

export alias "nutorch cos" = torch cos

# elementwise hyperbolic cosine
# usage: ahtch cosh <t1>
export def "ahtch cosh" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch cosh ...$__rest } else { $__in | ^ahtch cosh ...$__rest }
  $__out | str trim
}

export alias "nutorch cosh" = torch cosh

# degrees to radians
# usage: ahtch deg2rad <t1>
export def "ahtch deg2rad" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch deg2rad ...$__rest } else { $__in | ^ahtch deg2rad ...$__rest }
  $__out | str trim
}

export alias "nutorch deg2rad" = torch deg2rad

# elementwise digamma
# usage: ahtch digamma <t1>
export def "ahtch digamma" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch digamma ...$__rest } else { $__in | ^ahtch digamma ...$__rest }
  $__out | str trim
}

export alias "nutorch digamma" = torch digamma

# elementwise error function
# usage: ahtch erf <t1>
export def "ahtch erf" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch erf ...$__rest } else { $__in | ^ahtch erf ...$__rest }
  $__out | str trim
}

export alias "nutorch erf" = torch erf

# elementwise complementary error function
# usage: ahtch erfc <t1>
export def "ahtch erfc" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch erfc ...$__rest } else { $__in | ^ahtch erfc ...$__rest }
  $__out | str trim
}

export alias "nutorch erfc" = torch erfc

# elementwise e^x
# usage: ahtch exp <t1>
export def "ahtch exp" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch exp ...$__rest } else { $__in | ^ahtch exp ...$__rest }
  $__out | str trim
}

export alias "nutorch exp" = torch exp

# elementwise 2^x
# usage: ahtch exp2 <t1>
export def "ahtch exp2" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch exp2 ...$__rest } else { $__in | ^ahtch exp2 ...$__rest }
  $__out | str trim
}

export alias "nutorch exp2" = torch exp2

# elementwise e^x - 1
# usage: ahtch expm1 <t1>
export def "ahtch expm1" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch expm1 ...$__rest } else { $__in | ^ahtch expm1 ...$__rest }
  $__out | str trim
}

export alias "nutorch expm1" = torch expm1

# elementwise floor
# usage: ahtch floor <t1>
export def "ahtch floor" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch floor ...$__rest } else { $__in | ^ahtch floor ...$__rest }
  $__out | str trim
}

export alias "nutorch floor" = torch floor

# elementwise fractional part
# usage: ahtch frac <t1>
export def "ahtch frac" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch frac ...$__rest } else { $__in | ^ahtch frac ...$__rest }
  $__out | str trim
}

export alias "nutorch frac" = torch frac

# elementwise modified Bessel function I0
# usage: ahtch i0 <t1>
export def "ahtch i0" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch i0 ...$__rest } else { $__in | ^ahtch i0 ...$__rest }
  $__out | str trim
}

export alias "nutorch i0" = torch i0

# elementwise log-gamma
# usage: ahtch lgamma <t1>
export def "ahtch lgamma" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch lgamma ...$__rest } else { $__in | ^ahtch lgamma ...$__rest }
  $__out | str trim
}

export alias "nutorch lgamma" = torch lgamma

# elementwise natural log
# usage: ahtch log <t1>
export def "ahtch log" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch log ...$__rest } else { $__in | ^ahtch log ...$__rest }
  $__out | str trim
}

export alias "nutorch log" = torch log

# elementwise log base 10
# usage: ahtch log10 <t1>
export def "ahtch log10" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch log10 ...$__rest } else { $__in | ^ahtch log10 ...$__rest }
  $__out | str trim
}

export alias "nutorch log10" = torch log10

# elementwise log(1+x)
# usage: ahtch log1p <t1>
export def "ahtch log1p" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch log1p ...$__rest } else { $__in | ^ahtch log1p ...$__rest }
  $__out | str trim
}

export alias "nutorch log1p" = torch log1p

# elementwise log base 2
# usage: ahtch log2 <t1>
export def "ahtch log2" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch log2 ...$__rest } else { $__in | ^ahtch log2 ...$__rest }
  $__out | str trim
}

export alias "nutorch log2" = torch log2

# elementwise logit (inverse sigmoid)
# usage: ahtch logit <t1>
export def "ahtch logit" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logit ...$__rest } else { $__in | ^ahtch logit ...$__rest }
  $__out | str trim
}

export alias "nutorch logit" = torch logit

# elementwise negation
# usage: ahtch neg <t1>
export def "ahtch neg" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch neg ...$__rest } else { $__in | ^ahtch neg ...$__rest }
  $__out | str trim
}

export alias "nutorch neg" = torch neg

# radians to degrees
# usage: ahtch rad2deg <t1>
export def "ahtch rad2deg" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch rad2deg ...$__rest } else { $__in | ^ahtch rad2deg ...$__rest }
  $__out | str trim
}

export alias "nutorch rad2deg" = torch rad2deg

# elementwise 1/x
# usage: ahtch reciprocal <t1>
export def "ahtch reciprocal" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch reciprocal ...$__rest } else { $__in | ^ahtch reciprocal ...$__rest }
  $__out | str trim
}

export alias "nutorch reciprocal" = torch reciprocal

# elementwise max(x, 0)
# usage: ahtch relu <t1>
export def "ahtch relu" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch relu ...$__rest } else { $__in | ^ahtch relu ...$__rest }
  $__out | str trim
}

export alias "nutorch relu" = torch relu

# elementwise round to nearest
# usage: ahtch round <t1>
export def "ahtch round" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch round ...$__rest } else { $__in | ^ahtch round ...$__rest }
  $__out | str trim
}

export alias "nutorch round" = torch round

# elementwise 1/sqrt(x)
# usage: ahtch rsqrt <t1>
export def "ahtch rsqrt" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch rsqrt ...$__rest } else { $__in | ^ahtch rsqrt ...$__rest }
  $__out | str trim
}

export alias "nutorch rsqrt" = torch rsqrt

# elementwise sign (complex-aware)
# usage: ahtch sgn <t1>
export def "ahtch sgn" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sgn ...$__rest } else { $__in | ^ahtch sgn ...$__rest }
  $__out | str trim
}

export alias "nutorch sgn" = torch sgn

# elementwise sigmoid
# usage: ahtch sigmoid <t1>
export def "ahtch sigmoid" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sigmoid ...$__rest } else { $__in | ^ahtch sigmoid ...$__rest }
  $__out | str trim
}

export alias "nutorch sigmoid" = torch sigmoid

# elementwise sign
# usage: ahtch sign <t1>
export def "ahtch sign" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sign ...$__rest } else { $__in | ^ahtch sign ...$__rest }
  $__out | str trim
}

export alias "nutorch sign" = torch sign

# elementwise normalized sinc
# usage: ahtch sinc <t1>
export def "ahtch sinc" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sinc ...$__rest } else { $__in | ^ahtch sinc ...$__rest }
  $__out | str trim
}

export alias "nutorch sinc" = torch sinc

# elementwise hyperbolic sine
# usage: ahtch sinh <t1>
export def "ahtch sinh" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sinh ...$__rest } else { $__in | ^ahtch sinh ...$__rest }
  $__out | str trim
}

export alias "nutorch sinh" = torch sinh

# elementwise square root
# usage: ahtch sqrt <t1>
export def "ahtch sqrt" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch sqrt ...$__rest } else { $__in | ^ahtch sqrt ...$__rest }
  $__out | str trim
}

export alias "nutorch sqrt" = torch sqrt

# elementwise x^2
# usage: ahtch square <t1>
export def "ahtch square" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch square ...$__rest } else { $__in | ^ahtch square ...$__rest }
  $__out | str trim
}

export alias "nutorch square" = torch square

# elementwise tangent
# usage: ahtch tan <t1>
export def "ahtch tan" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch tan ...$__rest } else { $__in | ^ahtch tan ...$__rest }
  $__out | str trim
}

export alias "nutorch tan" = torch tan

# elementwise hyperbolic tangent
# usage: ahtch tanh <t1>
export def "ahtch tanh" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch tanh ...$__rest } else { $__in | ^ahtch tanh ...$__rest }
  $__out | str trim
}

export alias "nutorch tanh" = torch tanh

# elementwise truncation toward zero
# usage: ahtch trunc <t1>
export def "ahtch trunc" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch trunc ...$__rest } else { $__in | ^ahtch trunc ...$__rest }
  $__out | str trim
}

export alias "nutorch trunc" = torch trunc

# softmax along --dim (float32)
# usage: ahtch softmax <t1> [--dim <Int>]
export def "ahtch softmax" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch softmax ...$__rest ...$args } else { $__in | ^ahtch softmax ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch softmax" = torch softmax

# log-softmax along --dim (float32)
# usage: ahtch log_softmax <t1> [--dim <Int>]
export def "ahtch log_softmax" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch log_softmax ...$__rest ...$args } else { $__in | ^ahtch log_softmax ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch log_softmax" = torch log_softmax

# replace NaN/inf (--nan/--posinf/--neginf)
# usage: ahtch nan_to_num <t1> [--nan <Float>] [--posinf <Float>] [--neginf <Float>]
export def "ahtch nan_to_num" [...rest: any, --nan: number, --posinf: number, --neginf: number]: any -> string {
  mut args = []
  if $nan != null { $args = ($args | append ["--nan" ($nan | into string)]) }
  if $posinf != null { $args = ($args | append ["--posinf" ($posinf | into string)]) }
  if $neginf != null { $args = ($args | append ["--neginf" ($neginf | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch nan_to_num ...$__rest ...$args } else { $__in | ^ahtch nan_to_num ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch nan_to_num" = torch nan_to_num

# elementwise product (broadcasting)
# usage: ahtch mul <t1> <t2>
export def "ahtch mul" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch mul ...$__rest } else { $__in | ^ahtch mul ...$__rest }
  $__out | str trim
}

export alias "nutorch mul" = torch mul

# elementwise true division (broadcasting)
# usage: ahtch div <t1> <t2>
export def "ahtch div" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch div ...$__rest } else { $__in | ^ahtch div ...$__rest }
  $__out | str trim
}

export alias "nutorch div" = torch div

# elementwise maximum (broadcasting)
# usage: ahtch maximum <t1> <t2>
export def "ahtch maximum" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch maximum ...$__rest } else { $__in | ^ahtch maximum ...$__rest }
  $__out | str trim
}

export alias "nutorch maximum" = torch maximum

# elementwise minimum (broadcasting)
# usage: ahtch minimum <t1> <t2>
export def "ahtch minimum" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch minimum ...$__rest } else { $__in | ^ahtch minimum ...$__rest }
  $__out | str trim
}

export alias "nutorch minimum" = torch minimum

# elementwise atan2(a, b) (broadcasting)
# usage: ahtch atan2 <t1> <t2>
export def "ahtch atan2" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch atan2 ...$__rest } else { $__in | ^ahtch atan2 ...$__rest }
  $__out | str trim
}

export alias "nutorch atan2" = torch atan2

# elementwise C-style remainder (broadcasting)
# usage: ahtch fmod <t1> <t2>
export def "ahtch fmod" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch fmod ...$__rest } else { $__in | ^ahtch fmod ...$__rest }
  $__out | str trim
}

export alias "nutorch fmod" = torch fmod

# elementwise Python-style remainder (broadcasting)
# usage: ahtch remainder <t1> <t2>
export def "ahtch remainder" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch remainder ...$__rest } else { $__in | ^ahtch remainder ...$__rest }
  $__out | str trim
}

export alias "nutorch remainder" = torch remainder

# elementwise floor division (broadcasting)
# usage: ahtch floor_divide <t1> <t2>
export def "ahtch floor_divide" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch floor_divide ...$__rest } else { $__in | ^ahtch floor_divide ...$__rest }
  $__out | str trim
}

export alias "nutorch floor_divide" = torch floor_divide

# elementwise hypotenuse (broadcasting)
# usage: ahtch hypot <t1> <t2>
export def "ahtch hypot" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch hypot ...$__rest } else { $__in | ^ahtch hypot ...$__rest }
  $__out | str trim
}

export alias "nutorch hypot" = torch hypot

# magnitude of a, sign of b (broadcasting)
# usage: ahtch copysign <t1> <t2>
export def "ahtch copysign" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch copysign ...$__rest } else { $__in | ^ahtch copysign ...$__rest }
  $__out | str trim
}

export alias "nutorch copysign" = torch copysign

# elementwise x*log(y) (broadcasting)
# usage: ahtch xlogy <t1> <t2>
export def "ahtch xlogy" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch xlogy ...$__rest } else { $__in | ^ahtch xlogy ...$__rest }
  $__out | str trim
}

export alias "nutorch xlogy" = torch xlogy

# elementwise log(e^a + e^b) (broadcasting)
# usage: ahtch logaddexp <t1> <t2>
export def "ahtch logaddexp" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logaddexp ...$__rest } else { $__in | ^ahtch logaddexp ...$__rest }
  $__out | str trim
}

export alias "nutorch logaddexp" = torch logaddexp

# product over all elements, or along --dim
# usage: ahtch prod <t1> [--dim <Int>] [--keepdim]
export def "ahtch prod" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch prod ...$__rest ...$args } else { $__in | ^ahtch prod ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch prod" = torch prod

# max values over all elements, or along --dim
# usage: ahtch amax <t1> [--dim <Int>] [--keepdim]
export def "ahtch amax" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch amax ...$__rest ...$args } else { $__in | ^ahtch amax ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch amax" = torch amax

# min values over all elements, or along --dim
# usage: ahtch amin <t1> [--dim <Int>] [--keepdim]
export def "ahtch amin" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch amin ...$__rest ...$args } else { $__in | ^ahtch amin ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch amin" = torch amin

# max of all elements; with --dim also returns indices
# usage: ahtch max <t1> [--dim <Int>] [--keepdim]
export def "ahtch max" [...rest: any, --dim: int, --keepdim]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch max ...$__rest ...$args } else { $__in | ^ahtch max ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch max" = torch max

# min of all elements; with --dim also returns indices
# usage: ahtch min <t1> [--dim <Int>] [--keepdim]
export def "ahtch min" [...rest: any, --dim: int, --keepdim]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch min ...$__rest ...$args } else { $__in | ^ahtch min ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch min" = torch min

# median of all elements; with --dim also returns indices
# usage: ahtch median <t1> [--dim <Int>] [--keepdim]
export def "ahtch median" [...rest: any, --dim: int, --keepdim]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch median ...$__rest ...$args } else { $__in | ^ahtch median ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch median" = torch median

# index of the max, overall or along --dim
# usage: ahtch argmax <t1> [--dim <Int>] [--keepdim]
export def "ahtch argmax" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch argmax ...$__rest ...$args } else { $__in | ^ahtch argmax ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch argmax" = torch argmax

# index of the min, overall or along --dim
# usage: ahtch argmin <t1> [--dim <Int>] [--keepdim]
export def "ahtch argmin" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch argmin ...$__rest ...$args } else { $__in | ^ahtch argmin ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch argmin" = torch argmin

# true if all elements are true (Bool tensor)
# usage: ahtch all <t1> [--dim <Int>] [--keepdim]
export def "ahtch all" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch all ...$__rest ...$args } else { $__in | ^ahtch all ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch all" = torch all

# true if any element is true (Bool tensor)
# usage: ahtch any <t1> [--dim <Int>] [--keepdim]
export def "ahtch any" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch any ...$__rest ...$args } else { $__in | ^ahtch any ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch any" = torch any

# standard deviation (--correction, default 1)
# usage: ahtch std <t1> [--dim <Int>] [--keepdim] [--correction <Int>]
export def "ahtch std" [...rest: any, --dim: int, --keepdim, --correction: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  if $correction != null { $args = ($args | append ["--correction" ($correction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch std ...$__rest ...$args } else { $__in | ^ahtch std ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch std" = torch std

# variance (--correction, default 1)
# usage: ahtch var <t1> [--dim <Int>] [--keepdim] [--correction <Int>]
export def "ahtch var" [...rest: any, --dim: int, --keepdim, --correction: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  if $correction != null { $args = ($args | append ["--correction" ($correction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch var ...$__rest ...$args } else { $__in | ^ahtch var ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch var" = torch var

# sum treating NaN as zero
# usage: ahtch nansum <t1> [--dim <Int>] [--keepdim]
export def "ahtch nansum" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch nansum ...$__rest ...$args } else { $__in | ^ahtch nansum ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch nansum" = torch nansum

# log(sum(exp(x))) along --dim
# usage: ahtch logsumexp <t1> [--dim <Int>] [--keepdim]
export def "ahtch logsumexp" [...rest: any, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logsumexp ...$__rest ...$args } else { $__in | ^ahtch logsumexp ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch logsumexp" = torch logsumexp

# count of nonzero elements, overall or along --dim
# usage: ahtch count_nonzero <t1> [--dim <Int>]
export def "ahtch count_nonzero" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch count_nonzero ...$__rest ...$args } else { $__in | ^ahtch count_nonzero ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch count_nonzero" = torch count_nonzero

# cumulative sum along --dim
# usage: ahtch cumsum <t1> [--dim <Int>]
export def "ahtch cumsum" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch cumsum ...$__rest ...$args } else { $__in | ^ahtch cumsum ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch cumsum" = torch cumsum

# cumulative product along --dim
# usage: ahtch cumprod <t1> [--dim <Int>]
export def "ahtch cumprod" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch cumprod ...$__rest ...$args } else { $__in | ^ahtch cumprod ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch cumprod" = torch cumprod

# p-norm (--p default 2), overall or along --dim
# usage: ahtch norm <t1> [--p <Float>] [--dim <Int>] [--keepdim]
export def "ahtch norm" [...rest: any, --p: number, --dim: int, --keepdim]: any -> string {
  mut args = []
  if $p != null { $args = ($args | append ["--p" ($p | into string)]) }
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $keepdim { $args = ($args | append "--keepdim") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch norm ...$__rest ...$args } else { $__in | ^ahtch norm ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch norm" = torch norm

# elementwise a > b (Bool, broadcasting)
# usage: ahtch gt <t1> <t2>
export def "ahtch gt" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch gt ...$__rest } else { $__in | ^ahtch gt ...$__rest }
  $__out | str trim
}

export alias "nutorch gt" = torch gt

# elementwise a < b (Bool, broadcasting)
# usage: ahtch lt <t1> <t2>
export def "ahtch lt" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch lt ...$__rest } else { $__in | ^ahtch lt ...$__rest }
  $__out | str trim
}

export alias "nutorch lt" = torch lt

# elementwise a >= b (Bool, broadcasting)
# usage: ahtch ge <t1> <t2>
export def "ahtch ge" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch ge ...$__rest } else { $__in | ^ahtch ge ...$__rest }
  $__out | str trim
}

export alias "nutorch ge" = torch ge

# elementwise a <= b (Bool, broadcasting)
# usage: ahtch le <t1> <t2>
export def "ahtch le" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch le ...$__rest } else { $__in | ^ahtch le ...$__rest }
  $__out | str trim
}

export alias "nutorch le" = torch le

# elementwise a != b (Bool, broadcasting)
# usage: ahtch ne <t1> <t2>
export def "ahtch ne" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch ne ...$__rest } else { $__in | ^ahtch ne ...$__rest }
  $__out | str trim
}

export alias "nutorch ne" = torch ne

# elementwise logical AND (Bool, broadcasting)
# usage: ahtch logical_and <t1> <t2>
export def "ahtch logical_and" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logical_and ...$__rest } else { $__in | ^ahtch logical_and ...$__rest }
  $__out | str trim
}

export alias "nutorch logical_and" = torch logical_and

# elementwise logical OR (Bool, broadcasting)
# usage: ahtch logical_or <t1> <t2>
export def "ahtch logical_or" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logical_or ...$__rest } else { $__in | ^ahtch logical_or ...$__rest }
  $__out | str trim
}

export alias "nutorch logical_or" = torch logical_or

# elementwise logical XOR (Bool, broadcasting)
# usage: ahtch logical_xor <t1> <t2>
export def "ahtch logical_xor" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logical_xor ...$__rest } else { $__in | ^ahtch logical_xor ...$__rest }
  $__out | str trim
}

export alias "nutorch logical_xor" = torch logical_xor

# elementwise closeness (Bool; --rtol/--atol)
# usage: ahtch isclose <t1> <t2> [--rtol <Float>] [--atol <Float>]
export def "ahtch isclose" [...rest: any, --rtol: number, --atol: number]: any -> string {
  mut args = []
  if $rtol != null { $args = ($args | append ["--rtol" ($rtol | into string)]) }
  if $atol != null { $args = ($args | append ["--atol" ($atol | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch isclose ...$__rest ...$args } else { $__in | ^ahtch isclose ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch isclose" = torch isclose

# elementwise NaN test (Bool)
# usage: ahtch isnan <t1>
export def "ahtch isnan" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch isnan ...$__rest } else { $__in | ^ahtch isnan ...$__rest }
  $__out | str trim
}

export alias "nutorch isnan" = torch isnan

# elementwise infinity test (Bool)
# usage: ahtch isinf <t1>
export def "ahtch isinf" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch isinf ...$__rest } else { $__in | ^ahtch isinf ...$__rest }
  $__out | str trim
}

export alias "nutorch isinf" = torch isinf

# elementwise finiteness test (Bool)
# usage: ahtch isfinite <t1>
export def "ahtch isfinite" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch isfinite ...$__rest } else { $__in | ^ahtch isfinite ...$__rest }
  $__out | str trim
}

export alias "nutorch isfinite" = torch isfinite

# elementwise +inf test (Bool)
# usage: ahtch isposinf <t1>
export def "ahtch isposinf" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch isposinf ...$__rest } else { $__in | ^ahtch isposinf ...$__rest }
  $__out | str trim
}

export alias "nutorch isposinf" = torch isposinf

# elementwise -inf test (Bool)
# usage: ahtch isneginf <t1>
export def "ahtch isneginf" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch isneginf ...$__rest } else { $__in | ^ahtch isneginf ...$__rest }
  $__out | str trim
}

export alias "nutorch isneginf" = torch isneginf

# elementwise logical NOT (Bool)
# usage: ahtch logical_not <t1>
export def "ahtch logical_not" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch logical_not ...$__rest } else { $__in | ^ahtch logical_not ...$__rest }
  $__out | str trim
}

export alias "nutorch logical_not" = torch logical_not

# whole-tensor equality (returns a JSON bool)
# usage: ahtch equal <t1> <t2>
export def "ahtch equal" [...rest: any]: any -> any {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch equal ...$__rest } else { $__in | ^ahtch equal ...$__rest }
  $__out | from json | __nutorch-restore
}

export alias "nutorch equal" = torch equal

# top-k values+indices (--smallest = PyTorch largest=False, a nutorch-ism)
# usage: ahtch topk <t1> <k> [--dim <Int>] [--smallest]
export def "ahtch topk" [...rest: any, --dim: int, --smallest]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $smallest { $args = ($args | append "--smallest") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch topk ...$__rest ...$args } else { $__in | ^ahtch topk ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch topk" = torch topk

# indices that would sort along --dim (default last)
# usage: ahtch argsort <t1> [--dim <Int>] [--descending]
export def "ahtch argsort" [...rest: any, --dim: int, --descending]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  if $descending { $args = ($args | append "--descending") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch argsort ...$__rest ...$args } else { $__in | ^ahtch argsort ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch argsort" = torch argsort

# general matrix product (batched, PyTorch broadcasting)
# usage: ahtch matmul <t1> <t2>
export def "ahtch matmul" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch matmul ...$__rest } else { $__in | ^ahtch matmul ...$__rest }
  $__out | str trim
}

export alias "nutorch matmul" = torch matmul

# batched matrix multiply of two 3-D tensors
# usage: ahtch bmm <t1> <t2>
export def "ahtch bmm" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bmm ...$__rest } else { $__in | ^ahtch bmm ...$__rest }
  $__out | str trim
}

export alias "nutorch bmm" = torch bmm

# dot product of two 1-D tensors
# usage: ahtch dot <t1> <t2>
export def "ahtch dot" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch dot ...$__rest } else { $__in | ^ahtch dot ...$__rest }
  $__out | str trim
}

export alias "nutorch dot" = torch dot

# outer product of two 1-D tensors
# usage: ahtch outer <t1> <t2>
export def "ahtch outer" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch outer ...$__rest } else { $__in | ^ahtch outer ...$__rest }
  $__out | str trim
}

export alias "nutorch outer" = torch outer

# Einstein summation over --equation
export def "ahtch einsum" [...rest: string, --equation: string]: any -> string {
  mut args = []
  if $equation != null { $args = ($args | append ["--equation" ($equation | into string)]) }
  let __piped = $in
  let __text = if ($__piped | describe | str starts-with "list") { $__piped | str join (char newline) } else if $__piped == null { "" } else { $__piped }
  $__text | ^ahtch einsum ...$rest ...$args | str trim
}

export alias "nutorch einsum" = torch einsum

# lower triangle (--diagonal offset)
# usage: ahtch tril <t1> [--diagonal <Int>]
export def "ahtch tril" [...rest: any, --diagonal: int]: any -> string {
  mut args = []
  if $diagonal != null { $args = ($args | append ["--diagonal" ($diagonal | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch tril ...$__rest ...$args } else { $__in | ^ahtch tril ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch tril" = torch tril

# upper triangle (--diagonal offset)
# usage: ahtch triu <t1> [--diagonal <Int>]
export def "ahtch triu" [...rest: any, --diagonal: int]: any -> string {
  mut args = []
  if $diagonal != null { $args = ($args | append ["--diagonal" ($diagonal | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch triu ...$__rest ...$args } else { $__in | ^ahtch triu ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch triu" = torch triu

# diagonal of a matrix, or diagonal matrix from a vector
# usage: ahtch diag <t1> [--diagonal <Int>]
export def "ahtch diag" [...rest: any, --diagonal: int]: any -> string {
  mut args = []
  if $diagonal != null { $args = ($args | append ["--diagonal" ($diagonal | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch diag ...$__rest ...$args } else { $__in | ^ahtch diag ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch diag" = torch diag

# sum of the main diagonal of a 2-D tensor
# usage: ahtch trace <t1>
export def "ahtch trace" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch trace ...$__rest } else { $__in | ^ahtch trace ...$__rest }
  $__out | str trim
}

export alias "nutorch trace" = torch trace

# determinant of a square matrix
# usage: ahtch det <t1>
export def "ahtch det" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch det ...$__rest } else { $__in | ^ahtch det ...$__rest }
  $__out | str trim
}

export alias "nutorch det" = torch det

# inverse of a square matrix
# usage: ahtch inverse <t1>
export def "ahtch inverse" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch inverse ...$__rest } else { $__in | ^ahtch inverse ...$__rest }
  $__out | str trim
}

export alias "nutorch inverse" = torch inverse

# singular value decomposition (U, S, V)
# usage: ahtch svd <t1>
export def "ahtch svd" [...rest: any]: any -> list<string> {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch svd ...$__rest } else { $__in | ^ahtch svd ...$__rest }
  $__out | lines
}

export alias "nutorch svd" = torch svd

# solve AX = B for X
# usage: ahtch solve <t1> <t2>
export def "ahtch solve" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch solve ...$__rest } else { $__in | ^ahtch solve ...$__rest }
  $__out | str trim
}

export alias "nutorch solve" = torch solve

# reshape to the given shape (-1 infers one dim)
# usage: ahtch reshape <t1> <shape>
export def "ahtch reshape" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch reshape ...$__rest } else { $__in | ^ahtch reshape ...$__rest }
  $__out | str trim
}

export alias "nutorch reshape" = torch reshape

# permute dimensions
# usage: ahtch permute <t1> <dims>
export def "ahtch permute" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch permute ...$__rest } else { $__in | ^ahtch permute ...$__rest }
  $__out | str trim
}

export alias "nutorch permute" = torch permute

# swap two dimensions
# usage: ahtch transpose <t1> <dim0> <dim1>
export def "ahtch transpose" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch transpose ...$__rest } else { $__in | ^ahtch transpose ...$__rest }
  $__out | str trim
}

export alias "nutorch transpose" = torch transpose

# transpose a 2-D tensor
# usage: ahtch t <t1>
export def "ahtch t" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch t ...$__rest } else { $__in | ^ahtch t ...$__rest }
  $__out | str trim
}

export alias "nutorch t" = torch t

# drop size-1 dims (all, or --dim)
# usage: ahtch squeeze <t1> [--dim <Int>]
export def "ahtch squeeze" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch squeeze ...$__rest ...$args } else { $__in | ^ahtch squeeze ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch squeeze" = torch squeeze

# insert a size-1 dim
# usage: ahtch unsqueeze <t1> <dim>
export def "ahtch unsqueeze" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch unsqueeze ...$__rest } else { $__in | ^ahtch unsqueeze ...$__rest }
  $__out | str trim
}

export alias "nutorch unsqueeze" = torch unsqueeze

# flatten dims (--start_dim/--end_dim)
# usage: ahtch flatten <t1> [--start_dim <Int>] [--end_dim <Int>]
export def "ahtch flatten" [...rest: any, --start_dim: int, --end_dim: int]: any -> string {
  mut args = []
  if $start_dim != null { $args = ($args | append ["--start_dim" ($start_dim | into string)]) }
  if $end_dim != null { $args = ($args | append ["--end_dim" ($end_dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch flatten ...$__rest ...$args } else { $__in | ^ahtch flatten ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch flatten" = torch flatten

# stack tensors along a NEW --dim (default 0)
export def "ahtch stack" [...rest: string, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __piped = $in
  let __text = if ($__piped | describe | str starts-with "list") { $__piped | str join (char newline) } else if $__piped == null { "" } else { $__piped }
  $__text | ^ahtch stack ...$rest ...$args | str trim
}

export alias "nutorch stack" = torch stack

# split into chunks of split_size along --dim
# usage: ahtch split <t1> <split_size> [--dim <Int>]
export def "ahtch split" [...rest: any, --dim: int]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch split ...$__rest ...$args } else { $__in | ^ahtch split ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch split" = torch split

# split into N chunks along --dim
# usage: ahtch chunk <t1> <chunks> [--dim <Int>]
export def "ahtch chunk" [...rest: any, --dim: int]: any -> list<string> {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch chunk ...$__rest ...$args } else { $__in | ^ahtch chunk ...$__rest ...$args }
  $__out | lines
}

export alias "nutorch chunk" = torch chunk

# gather values along --dim using an int64 index tensor
# usage: ahtch gather <t1> <t2> [--dim <Int>]
export def "ahtch gather" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch gather ...$__rest ...$args } else { $__in | ^ahtch gather ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch gather" = torch gather

# select rows/cols along --dim by an int64 index tensor
# usage: ahtch index_select <t1> <t2> [--dim <Int>]
export def "ahtch index_select" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch index_select ...$__rest ...$args } else { $__in | ^ahtch index_select ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch index_select" = torch index_select

# select by mask (numeric mask cast via != 0, a nutorch-ism)
# usage: ahtch masked_select <t1> <t2>
export def "ahtch masked_select" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch masked_select ...$__rest } else { $__in | ^ahtch masked_select ...$__rest }
  $__out | str trim
}

export alias "nutorch masked_select" = torch masked_select

# cond ? x : y (numeric cond cast via != 0, a nutorch-ism)
# usage: ahtch where <t1> <t2> <t3>
export def "ahtch where" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch where ...$__rest } else { $__in | ^ahtch where ...$__rest }
  $__out | str trim
}

export alias "nutorch where" = torch where

# slice: length elements from start along dim
# usage: ahtch narrow <t1> <dim> <start> <length>
export def "ahtch narrow" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch narrow ...$__rest } else { $__in | ^ahtch narrow ...$__rest }
  $__out | str trim
}

export alias "nutorch narrow" = torch narrow

# reverse along the given dims
# usage: ahtch flip <t1> <dims>
export def "ahtch flip" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch flip ...$__rest } else { $__in | ^ahtch flip ...$__rest }
  $__out | str trim
}

export alias "nutorch flip" = torch flip

# roll elements by shifts (optionally along --dims)
# usage: ahtch roll <t1> <shifts> [--dims <IntList>]
export def "ahtch roll" [...rest: any, --dims: list<int>]: any -> string {
  mut args = []
  if $dims != null { $args = ($args | append ["--dims" ($dims | to json -r)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch roll ...$__rest ...$args } else { $__in | ^ahtch roll ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch roll" = torch roll

# tile the tensor by repeats per dim
# usage: ahtch repeat <t1> <repeats>
export def "ahtch repeat" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch repeat ...$__rest } else { $__in | ^ahtch repeat ...$__rest }
  $__out | str trim
}

export alias "nutorch repeat" = torch repeat

# repeat each element N times (optionally along --dim)
# usage: ahtch repeat_interleave <t1> <repeats> [--dim <Int>]
export def "ahtch repeat_interleave" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch repeat_interleave ...$__rest ...$args } else { $__in | ^ahtch repeat_interleave ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch repeat_interleave" = torch repeat_interleave

# move a dim to a new position
# usage: ahtch movedim <t1> <source> <destination>
export def "ahtch movedim" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch movedim ...$__rest } else { $__in | ^ahtch movedim ...$__rest }
  $__out | str trim
}

export alias "nutorch movedim" = torch movedim

# a tensor of zeros
export def "ahtch zeros" [shape: list<int>, --dtype: string, --requires_grad]: nothing -> string {
  mut args = []
  if $dtype != null { $args = ($args | append ["--dtype" ($dtype | into string)]) }
  if $requires_grad { $args = ($args | append "--requires_grad") }
  ^ahtch zeros ($shape | to json -r) ...$args | str trim
}

export alias "nutorch zeros" = torch zeros

# a tensor of ones
export def "ahtch ones" [shape: list<int>, --dtype: string, --requires_grad]: nothing -> string {
  mut args = []
  if $dtype != null { $args = ($args | append ["--dtype" ($dtype | into string)]) }
  if $requires_grad { $args = ($args | append "--requires_grad") }
  ^ahtch ones ($shape | to json -r) ...$args | str trim
}

export alias "nutorch ones" = torch ones

# identity matrix (n x n, or n x --m)
export def "ahtch eye" [n: int, --m: int]: nothing -> string {
  mut args = []
  if $m != null { $args = ($args | append ["--m" ($m | into string)]) }
  ^ahtch eye ($n | into string) ...$args | str trim
}

export alias "nutorch eye" = torch eye

# range [--start, end) by --step (CLI reshape of PyTorch overloads)
export def "ahtch arange" [end: number, --start: number, --step: number]: nothing -> string {
  mut args = []
  if $start != null { $args = ($args | append ["--start" ($start | into string)]) }
  if $step != null { $args = ($args | append ["--step" ($step | into string)]) }
  ^ahtch arange ($end | into string) ...$args | str trim
}

export alias "nutorch arange" = torch arange

# steps evenly spaced points in [start, end]
export def "ahtch linspace" [start: number, end: number, steps: int]: nothing -> string {
  ^ahtch linspace ($start | into string) ($end | into string) ($steps | into string) | str trim
}

export alias "nutorch linspace" = torch linspace

# uniform [0,1) random tensor (seeded CPU generator)
export def "ahtch rand" [shape: list<int>, --requires_grad]: nothing -> string {
  mut args = []
  if $requires_grad { $args = ($args | append "--requires_grad") }
  ^ahtch rand ($shape | to json -r) ...$args | str trim
}

export alias "nutorch rand" = torch rand

# random int64s in [--low, high) (seeded CPU generator)
export def "ahtch randint" [high: int, shape: list<int>, --low: int]: nothing -> string {
  mut args = []
  if $low != null { $args = ($args | append ["--low" ($low | into string)]) }
  ^ahtch randint ($high | into string) ($shape | to json -r) ...$args | str trim
}

export alias "nutorch randint" = torch randint

# zeros with the input's shape and dtype
# usage: ahtch zeros_like <t1>
export def "ahtch zeros_like" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch zeros_like ...$__rest } else { $__in | ^ahtch zeros_like ...$__rest }
  $__out | str trim
}

export alias "nutorch zeros_like" = torch zeros_like

# ones with the input's shape and dtype
# usage: ahtch ones_like <t1>
export def "ahtch ones_like" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch ones_like ...$__rest } else { $__in | ^ahtch ones_like ...$__rest }
  $__out | str trim
}

export alias "nutorch ones_like" = torch ones_like

# a value-filled tensor with the input's shape and dtype
# usage: ahtch full_like <t1> <value>
export def "ahtch full_like" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch full_like ...$__rest } else { $__in | ^ahtch full_like ...$__rest }
  $__out | str trim
}

export alias "nutorch full_like" = torch full_like

# uniform random with the input's shape (seeded CPU generator)
# usage: ahtch rand_like <t1>
export def "ahtch rand_like" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch rand_like ...$__rest } else { $__in | ^ahtch rand_like ...$__rest }
  $__out | str trim
}

export alias "nutorch rand_like" = torch rand_like

# normal random with the input's shape (seeded CPU generator)
# usage: ahtch randn_like <t1>
export def "ahtch randn_like" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch randn_like ...$__rest } else { $__in | ^ahtch randn_like ...$__rest }
  $__out | str trim
}

export alias "nutorch randn_like" = torch randn_like

# a + weight*(b - a) (scalar or tensor weight)
# usage: ahtch lerp <t1> <t2> <weight>
export def "ahtch lerp" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch lerp ...$__rest } else { $__in | ^ahtch lerp ...$__rest }
  $__out | str trim
}

export alias "nutorch lerp" = torch lerp

# a + value * b * c
# usage: ahtch addcmul <t1> <t2> <t3> [--value <Scalar>]
export def "ahtch addcmul" [...rest: any, --value: number]: any -> string {
  mut args = []
  if $value != null { $args = ($args | append ["--value" ($value | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch addcmul ...$__rest ...$args } else { $__in | ^ahtch addcmul ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch addcmul" = torch addcmul

# a + value * b / c
# usage: ahtch addcdiv <t1> <t2> <t3> [--value <Scalar>]
export def "ahtch addcdiv" [...rest: any, --value: number]: any -> string {
  mut args = []
  if $value != null { $args = ($args | append ["--value" ($value | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch addcdiv ...$__rest ...$args } else { $__in | ^ahtch addcdiv ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch addcdiv" = torch addcdiv

# vector cross product along --dim
# usage: ahtch cross <t1> <t2> [--dim <Int>]
export def "ahtch cross" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch cross ...$__rest ...$args } else { $__in | ^ahtch cross ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch cross" = torch cross

# Kronecker product
# usage: ahtch kron <t1> <t2>
export def "ahtch kron" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch kron ...$__rest } else { $__in | ^ahtch kron ...$__rest }
  $__out | str trim
}

export alias "nutorch kron" = torch kron

# tensor contraction over the last/first --dims dims (default 2)
# usage: ahtch tensordot <t1> <t2> [--dims <Int>]
export def "ahtch tensordot" [...rest: any, --dims: int]: any -> string {
  mut args = []
  if $dims != null { $args = ($args | append ["--dims" ($dims | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch tensordot ...$__rest ...$args } else { $__in | ^ahtch tensordot ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch tensordot" = torch tensordot

# gather along --dim with a broadcastable int64 index
# usage: ahtch take_along_dim <t1> <t2> [--dim <Int>]
export def "ahtch take_along_dim" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch take_along_dim ...$__rest ...$args } else { $__in | ^ahtch take_along_dim ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch take_along_dim" = torch take_along_dim

# insertion indices: searchsorted(sorted_seq, values)
# usage: ahtch searchsorted <t1> <t2>
export def "ahtch searchsorted" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch searchsorted ...$__rest } else { $__in | ^ahtch searchsorted ...$__rest }
  $__out | str trim
}

export alias "nutorch searchsorted" = torch searchsorted

# bucket indices: bucketize(values, boundaries)
# usage: ahtch bucketize <t1> <t2>
export def "ahtch bucketize" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bucketize ...$__rest } else { $__in | ^ahtch bucketize ...$__rest }
  $__out | str trim
}

export alias "nutorch bucketize" = torch bucketize

# sort along the first dimension (values only)
# usage: ahtch msort <t1>
export def "ahtch msort" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch msort ...$__rest } else { $__in | ^ahtch msort ...$__rest }
  $__out | str trim
}

export alias "nutorch msort" = torch msort

# forward differences along --dim (default last)
# usage: ahtch diff <t1> [--dim <Int>]
export def "ahtch diff" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch diff ...$__rest ...$args } else { $__in | ^ahtch diff ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch diff" = torch diff

# non-inplace scatter: input, int64 index, src along --dim
# usage: ahtch scatter <t1> <t2> <t3> [--dim <Int>]
export def "ahtch scatter" [...rest: any, --dim: int]: any -> string {
  mut args = []
  if $dim != null { $args = ($args | append ["--dim" ($dim | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch scatter ...$__rest ...$args } else { $__in | ^ahtch scatter ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch scatter" = torch scatter

# bitwise AND of int tensors (broadcasting)
# usage: ahtch bitwise_and <t1> <t2>
export def "ahtch bitwise_and" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bitwise_and ...$__rest } else { $__in | ^ahtch bitwise_and ...$__rest }
  $__out | str trim
}

export alias "nutorch bitwise_and" = torch bitwise_and

# bitwise OR of int tensors (broadcasting)
# usage: ahtch bitwise_or <t1> <t2>
export def "ahtch bitwise_or" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bitwise_or ...$__rest } else { $__in | ^ahtch bitwise_or ...$__rest }
  $__out | str trim
}

export alias "nutorch bitwise_or" = torch bitwise_or

# bitwise XOR of int tensors (broadcasting)
# usage: ahtch bitwise_xor <t1> <t2>
export def "ahtch bitwise_xor" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bitwise_xor ...$__rest } else { $__in | ^ahtch bitwise_xor ...$__rest }
  $__out | str trim
}

export alias "nutorch bitwise_xor" = torch bitwise_xor

# bitwise NOT of an int tensor
# usage: ahtch bitwise_not <t1>
export def "ahtch bitwise_not" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bitwise_not ...$__rest } else { $__in | ^ahtch bitwise_not ...$__rest }
  $__out | str trim
}

export alias "nutorch bitwise_not" = torch bitwise_not

# left shift of int tensors (broadcasting)
# usage: ahtch bitwise_left_shift <t1> <t2>
export def "ahtch bitwise_left_shift" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bitwise_left_shift ...$__rest } else { $__in | ^ahtch bitwise_left_shift ...$__rest }
  $__out | str trim
}

export alias "nutorch bitwise_left_shift" = torch bitwise_left_shift

# right shift of int tensors (broadcasting)
# usage: ahtch bitwise_right_shift <t1> <t2>
export def "ahtch bitwise_right_shift" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch bitwise_right_shift ...$__rest } else { $__in | ^ahtch bitwise_right_shift ...$__rest }
  $__out | str trim
}

export alias "nutorch bitwise_right_shift" = torch bitwise_right_shift

# sorted unique values
# usage: ahtch unique <t1>
export def "ahtch unique" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch unique ...$__rest } else { $__in | ^ahtch unique ...$__rest }
  $__out | str trim
}

export alias "nutorch unique" = torch unique

# backpropagate from a scalar loss (gradients accumulate)
# usage: ahtch backward <t1>
export def "ahtch backward" [...rest: any]: any -> nothing {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch backward ...$__rest } else { $__in | ^ahtch backward ...$__rest }
  $__out | ignore
}

export alias "nutorch backward" = torch backward

# snapshot of a tensor's accumulated gradient
# usage: ahtch grad <t1>
export def "ahtch grad" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch grad ...$__rest } else { $__in | ^ahtch grad ...$__rest }
  $__out | str trim
}

export alias "nutorch grad" = torch grad

# a graph-free reference to the same data
# usage: ahtch detach <t1>
export def "ahtch detach" [...rest: any]: any -> string {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch detach ...$__rest } else { $__in | ^ahtch detach ...$__rest }
  $__out | str trim
}

export alias "nutorch detach" = torch detach

# zero a tensor's accumulated gradient in place
# usage: ahtch zero_grad <t1>
export def "ahtch zero_grad" [...rest: any]: any -> nothing {
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch zero_grad ...$__rest } else { $__in | ^ahtch zero_grad ...$__rest }
  $__out | ignore
}

export alias "nutorch zero_grad" = torch zero_grad

# mean squared error (--reduction mean|sum|none)
# usage: ahtch mse_loss <t1> <t2> [--reduction <Str>]
export def "ahtch mse_loss" [...rest: any, --reduction: string]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch mse_loss ...$__rest ...$args } else { $__in | ^ahtch mse_loss ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch mse_loss" = torch mse_loss

# mean absolute error (--reduction)
# usage: ahtch l1_loss <t1> <t2> [--reduction <Str>]
export def "ahtch l1_loss" [...rest: any, --reduction: string]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch l1_loss ...$__rest ...$args } else { $__in | ^ahtch l1_loss ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch l1_loss" = torch l1_loss

# smooth L1 loss (--beta, default 1.0)
# usage: ahtch smooth_l1_loss <t1> <t2> [--reduction <Str>] [--beta <Float>]
export def "ahtch smooth_l1_loss" [...rest: any, --reduction: string, --beta: number]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  if $beta != null { $args = ($args | append ["--beta" ($beta | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch smooth_l1_loss ...$__rest ...$args } else { $__in | ^ahtch smooth_l1_loss ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch smooth_l1_loss" = torch smooth_l1_loss

# Huber loss (--delta, default 1.0)
# usage: ahtch huber_loss <t1> <t2> [--reduction <Str>] [--delta <Float>]
export def "ahtch huber_loss" [...rest: any, --reduction: string, --delta: number]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  if $delta != null { $args = ($args | append ["--delta" ($delta | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch huber_loss ...$__rest ...$args } else { $__in | ^ahtch huber_loss ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch huber_loss" = torch huber_loss

# cross entropy over logits vs int64 class indices
# usage: ahtch cross_entropy <t1> <t2> [--reduction <Str>]
export def "ahtch cross_entropy" [...rest: any, --reduction: string]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch cross_entropy ...$__rest ...$args } else { $__in | ^ahtch cross_entropy ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch cross_entropy" = torch cross_entropy

# negative log likelihood (log-prob inputs, int64 targets)
# usage: ahtch nll_loss <t1> <t2> [--reduction <Str>]
export def "ahtch nll_loss" [...rest: any, --reduction: string]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch nll_loss ...$__rest ...$args } else { $__in | ^ahtch nll_loss ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch nll_loss" = torch nll_loss

# BCE over probabilities in [0,1]
# usage: ahtch binary_cross_entropy <t1> <t2> [--reduction <Str>]
export def "ahtch binary_cross_entropy" [...rest: any, --reduction: string]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch binary_cross_entropy ...$__rest ...$args } else { $__in | ^ahtch binary_cross_entropy ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch binary_cross_entropy" = torch binary_cross_entropy

# BCE over logits (the stable form)
# usage: ahtch binary_cross_entropy_with_logits <t1> <t2> [--reduction <Str>]
export def "ahtch binary_cross_entropy_with_logits" [...rest: any, --reduction: string]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch binary_cross_entropy_with_logits ...$__rest ...$args } else { $__in | ^ahtch binary_cross_entropy_with_logits ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch binary_cross_entropy_with_logits" = torch binary_cross_entropy_with_logits

# KL divergence (--log_target if target is log-space)
# usage: ahtch kl_div <t1> <t2> [--reduction <Str>] [--log_target]
export def "ahtch kl_div" [...rest: any, --reduction: string, --log_target]: any -> string {
  mut args = []
  if $reduction != null { $args = ($args | append ["--reduction" ($reduction | into string)]) }
  if $log_target { $args = ($args | append "--log_target") }
  let __rest = ($rest | each {|a| if ($a | describe | str starts-with "list") { $a | to json -r } else { $a | into string } })
  let __in = $in
  let __out = if $__in == null { ^ahtch kl_div ...$__rest ...$args } else { $__in | ^ahtch kl_div ...$__rest ...$args }
  $__out | str trim
}

export alias "nutorch kl_div" = torch kl_div

# seed the random number generator
export def "ahtch manual_seed" [seed: int]: nothing -> nothing {
  ^ahtch manual_seed ($seed | into string) | ignore
}

export alias "nutorch manual_seed" = torch manual_seed
